# Generated by Django 2.2.2 on 2020-03-05 11:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dienthoai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Huong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiBDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhapLy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateBaiViet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baiviet', models.TextField(max_length=200, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Mẫu tin',
                'verbose_name_plural': 'Mẫu tin',
            },
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tinh')),
            ],
        ),
        migrations.CreateModel(
            name='PhuongXa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('huyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.QuanHuyen')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Mô tả')),
                ('gia_tien', models.FloatField(verbose_name='Giá tiền')),
                ('dientich', models.IntegerField(verbose_name='Diện tích')),
                ('sotang', models.IntegerField(verbose_name='Số tầng')),
                ('so_phong_ngu', models.IntegerField(default=0, verbose_name='Số phòng ngủ')),
                ('co_mat_tien', models.BooleanField(default=False)),
                ('mattien', models.FloatField(verbose_name='Mặt tiền')),
                ('dia_chi', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('trang_thai_nha', models.BooleanField(default=False, verbose_name='Trạng thái nhà')),
                ('co_nha_bep', models.BooleanField(default=False, verbose_name='Có nhà bếp')),
                ('co_phong_an', models.BooleanField(default=False, verbose_name='Có phòng ăn')),
                ('co_san_thuong', models.BooleanField(default=False, verbose_name='Có sân thượng')),
                ('co_cho_de_xe_hoi', models.BooleanField(default=False, verbose_name='Có chỗ để xe hơi')),
                ('anh_1', models.ImageField(blank=True, null=True, upload_to='anh_nha')),
                ('anh_2', models.ImageField(blank=True, null=True, upload_to='anh_nha')),
                ('anh_3', models.ImageField(blank=True, null=True, upload_to='anh_nha')),
                ('anh_4', models.ImageField(blank=True, null=True, upload_to='anh_nha')),
                ('anh_5', models.ImageField(blank=True, null=True, upload_to='anh_nha')),
                ('loai_bds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LoaiBDS', verbose_name='Loại BDS')),
                ('loai_tin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LoaiTin', verbose_name='Loại tin')),
                ('phaply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PhapLy', verbose_name='Pháp lý')),
            ],
            options={
                'verbose_name': 'Nhà',
                'verbose_name_plural': 'Nhà đất',
            },
        ),
        migrations.CreateModel(
            name='DuongPho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('phuongxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PhuongXa')),
            ],
        ),
        migrations.CreateModel(
            name='DuAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('phuongxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DuongPho')),
            ],
        ),
    ]
