# Generated by Django 2.2.2 on 2020-02-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=200)),
                ('gia_tien', models.IntegerField()),
                ('dientich', models.IntegerField()),
                ('sotang', models.IntegerField()),
                ('co_mat_tien', models.BooleanField(default=False)),
                ('mattien', models.FloatField()),
                ('dia_chi', models.CharField(max_length=200)),
                ('trang_thai_nha', models.IntegerField(choices=[(0, 'Nhà chưa bán'), (1, 'Nhà đã bán')])),
            ],
        ),
    ]
