# Generated by Django 2.2.2 on 2020-02-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='trang_thai_nha',
            field=models.BooleanField(default=False),
        ),
    ]
