# Generated by Django 2.2.2 on 2020-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200226_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Nhà', 'verbose_name_plural': 'Nhà đất'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='dia_chi',
            field=models.CharField(max_length=200, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='dientich',
            field=models.IntegerField(verbose_name='Diện tích'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='gia_tien',
            field=models.IntegerField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='mattien',
            field=models.FloatField(verbose_name='Mặt tiền'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='sotang',
            field=models.IntegerField(verbose_name='Số tầng'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='trang_thai_nha',
            field=models.BooleanField(choices=[(0, 'Nhà chưa bán'), (1, 'Nhà đã bán')], default=False, verbose_name='Trạng thái nhà'),
        ),
    ]
