# Generated by Django 2.2.2 on 2020-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200226_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBaiViet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baiviet', models.TextField(max_length=200, verbose_name='Mô tả')),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='anh_1',
            field=models.ImageField(null=True, upload_to='anh_nha'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='anh_2',
            field=models.ImageField(null=True, upload_to='anh_nha'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='anh_3',
            field=models.ImageField(null=True, upload_to='anh_nha'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='anh_4',
            field=models.ImageField(null=True, upload_to='anh_nha'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='anh_5',
            field=models.ImageField(null=True, upload_to='anh_nha'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='trang_thai_nha',
            field=models.BooleanField(default=False, verbose_name='Trạng thái nhà'),
        ),
    ]
