# Generated by Django 2.2.2 on 2020-02-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200226_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='anh_1',
            field=models.ImageField(blank=True, null=True, upload_to='anh_nha'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='anh_2',
            field=models.ImageField(blank=True, null=True, upload_to='anh_nha'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='anh_3',
            field=models.ImageField(blank=True, null=True, upload_to='anh_nha'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='anh_4',
            field=models.ImageField(blank=True, null=True, upload_to='anh_nha'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='anh_5',
            field=models.ImageField(blank=True, null=True, upload_to='anh_nha'),
        ),
    ]
