# Generated by Django 2.2.2 on 2020-02-27 02:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200226_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatebaiviet',
            options={'verbose_name': 'Mẫu tin', 'verbose_name_plural': 'Mẫu tin'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Mô tả'),
        ),
    ]
