# Generated by Django 2.2.2 on 2020-02-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200227_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='gia_tien',
            field=models.IntegerField(verbose_name='Giá tiền'),
        ),
    ]
